### ISSUE TITLE
ModuleNotFoundError: No module named 'vedbus'

### ISSUE THREAD

**Issue by ErazorVIP** [kopierschnitte/venus.dbus-senec-enfluri#4]
Hello,

i get following error when i start the smartmeter... I ajdjust all path to iobroker.

File "dbus-iobroker-smartmeter.py", line 4, in <module>
    from vedbus import VeDbusService
ModuleNotFoundError: No module named 'vedbus'

Can u help me?

**Comment by kopierschnitte** [comment]
Hello!
That applies to the forked version (for ioBroker) and not this repository (which is for EnFluRi). Sorry, please open the issue there.
