### ISSUE TITLE
Keine Verbindung mehr zum Senec seit Firmware-update

### ISSUE THREAD

**Issue by MIC1981** [kopierschnitte/venus.dbus-senec-enfluri#6]
Senec hat auf https umgestellt. Daher ist momentan keine Verbindung möglich. Gibt es hierzu schon eine Lösung? Eine Änderung der Adresse auf https in der python-Datei brachte keine Änderung.

**Comment by kopierschnitte** [comment]
Leider noch keine Lösung. Senec hat auch sehr viele Datenpunkte entfernt ... daher stehe ich momentan auf dem Schlauch.

**Comment by kopierschnitte** [comment]
So, jetzt müsste es klappen. Ansonsten bitte neuen Issue öffnen.
Leider hakt es noch ab und wann und der Gesamtverbrauch wurde leider von Senec entfernt.
